# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dive < Formula
  desc "A tool for exploring layers in a docker image"
  homepage "https://github.com/joschi/dive/"
  version "0.13.0-alpha.3"

  on_macos do
    on_intel do
      url "https://github.com/joschi/dive/releases/download/v0.13.0-alpha.3/dive_0.13.0-alpha.3_darwin_amd64.tar.gz"
      sha256 "4b867ba3af09b9bccf94762b5f7a05596411d2f64fb50031608ce450205e9f40"

      def install
        bin.install "dive"
      end
    end
    on_arm do
      url "https://github.com/joschi/dive/releases/download/v0.13.0-alpha.3/dive_0.13.0-alpha.3_darwin_arm64.tar.gz"
      sha256 "254afcf35423d74d821f639efd729e2b8366c3149e6ae2707545b48f6928eb88"

      def install
        bin.install "dive"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joschi/dive/releases/download/v0.13.0-alpha.3/dive_0.13.0-alpha.3_linux_amd64.tar.gz"
        sha256 "4f35e78821b444a08b7ccbe6151bac47f0f29d77c9aa005c96f98af5d2e16b2e"

        def install
          bin.install "dive"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joschi/dive/releases/download/v0.13.0-alpha.3/dive_0.13.0-alpha.3_linux_arm64.tar.gz"
        sha256 "d6a4653973c2d721ba76acb4dc22c7b024ec706dd38226281edfb45fd66c6685"

        def install
          bin.install "dive"
        end
      end
    end
  end
end
