# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dive < Formula
  desc "A tool for exploring layers in a docker image"
  homepage "https://github.com/joschi/dive/"
  version "0.14.0"

  on_macos do
    on_intel do
      url "https://github.com/joschi/dive/releases/download/v0.14.0/dive_0.14.0_darwin_amd64.tar.gz"
      sha256 "cfbcccb9714206eece925df34d8416dc07c2edd7685c2afbcc3e38113b20eed0"

      def install
        bin.install "dive"
      end
    end
    on_arm do
      url "https://github.com/joschi/dive/releases/download/v0.14.0/dive_0.14.0_darwin_arm64.tar.gz"
      sha256 "8549c609629fece9ebec0f2a2b00d6011350b4928dfd8d47ddd91dbe49328c18"

      def install
        bin.install "dive"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joschi/dive/releases/download/v0.14.0/dive_0.14.0_linux_amd64.tar.gz"
        sha256 "256f1857a559cbfabecb083b1654108dde78f7a5de950a0e5510c2924fdf3fe5"

        def install
          bin.install "dive"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joschi/dive/releases/download/v0.14.0/dive_0.14.0_linux_arm64.tar.gz"
        sha256 "af130557927186998a334ccf6c68755bf6b1e9959c216629aeb2afe14ba0ab88"

        def install
          bin.install "dive"
        end
      end
    end
  end
end
